### ISSUE TITLE
Muse Sounds Manager V2

### ISSUE THREAD

**Issue by DominicMaas** [neferin12/muse-sounds-manager-aur#2]
Hey, developer of Muse Sounds Manager here,

As a heads up, we're prepping to release v2 of Muse Sounds Manager, not too many changes, but we're going to provide a .tar.gz which contains a bin folder for the actual executable + required libraries alongside a .desktop file and the icon resources.

This would probably be preferable to repacking the deb as the tar.gz version has the built in updater disabled.

Here's the current structure of the tar.gz:

```
muse_sounds_manager_x64_2.0.0.0/
muse_sounds_manager_x64_2.0.0.0/README.txt
muse_sounds_manager_x64_2.0.0.0/res/
muse_sounds_manager_x64_2.0.0.0/res/muse-sounds-manager.desktop
muse_sounds_manager_x64_2.0.0.0/res/icons/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/128x128/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/128x128/apps/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/128x128/apps/muse-sounds-manager.png
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/48x48/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/48x48/apps/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/48x48/apps/muse-sounds-manager.png
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/64x64/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/64x64/apps/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/64x64/apps/muse-sounds-manager.png
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/256x256/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/256x256/apps/
muse_sounds_manager_x64_2.0.0.0/res/icons/hicolor/256x256/apps/muse-sounds-manager.png
muse_sounds_manager_x64_2.0.0.0/bin/
muse_sounds_manager_x64_2.0.0.0/bin/libSkiaSharp.so
muse_sounds_manager_x64_2.0.0.0/bin/muse-sounds-manager
muse_sounds_manager_x64_2.0.0.0/bin/libServiceCore.so
muse_sounds_manager_x64_2.0.0.0/bin/libHarfBuzzSharp.so
```

I'll comment on this issue once we have a version released!

Also if there's anything else you need, or anything that'll make repacking easier for arch, just let me know!

**Comment by DominicMaas** [comment]
And we're live with the CDN link! It hasn't been announced quite yet, and I would consider this an RC build until we get some feedback / ensure there are no major issues.

http://muse-cdn.com/Muse_Sounds_Manager_x64.tar.gz

**Comment by DominicMaas** [comment]
there doesn't seem to be any major issues tracking on our end. We're probably going to start pushing this version out to our automatic updater.

I've also left some minor comments on the v2 branch

**Comment by neferin12** [comment]
That's good to hear, I will also merge the update for the package then. Thank you very much for your heads up and feedback.
